export type Source = { title?: string; url?: string; content?: string; source?: string; fact?: string };
export type AgentNode = { id: string; data?: { label?: string; agent_name?: string; status?: string } };
export type Intelligence = { company?: string | null; roles?: string[]; locations?: string[]; hiring_signals?: string[]; technology_signals?: string[]; expansion_signals?: string[]; funding_events?: { round?: string | null; amount?: string | null; investors?: string[]; date?: string | null; source_url?: string | null }[]; latest_round?: string | null; investors?: string[]; total_known_funding?: string | null; sources?: Source[] };
export type Memory = { status?: 'available'|'empty'|'unavailable'; first_investigation?: boolean; company?: string; relevant_memories?: { content?: string }[]; historical_intelligence?: { content?: string }[]; historical_signals?: string[]; previous_recommendation?: string | null; changes?: string | null; retain_status?: string };
export type Mission = { id: string; title?: string; objective: string; domain?: string; status: string; created_at?: string; updated_at?: string; strategy?: { industry?: string; countries?: string[] }; shared_memory?: Record<string, unknown>; execution_graph?: { nodes?: AgentNode[] } };
export type MissionRunResponse = { mission_id: string; status: string; strategy?: Record<string, unknown> | null; planner?: { execution_graph?: { nodes?: AgentNode[] }; shared_memory?: Record<string, unknown> } | null; shared_memory: Record<string, unknown>; memory: Memory; confidence: number };
export type MissionListResponse = { items: Mission[]; total: number };
const baseUrl = process.env.NEXT_PUBLIC_AION_API_URL || 'http://127.0.0.1:8000';
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${baseUrl}${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers }, cache: 'no-store' }); if (!response.ok) throw new Error('AION could not complete this request.'); return response.json() as Promise<T>; }
export const missionsApi = { create: (objective: string, domain?: string) => request<MissionRunResponse>('/api/v1/missions/create', { method: 'POST', body: JSON.stringify({ title: objective, objective, domain: domain || null }) }), get: (id: string) => request<Mission>(`/api/v1/missions/${id}`), list: () => request<MissionListResponse>('/api/v1/missions') };
